type User {
	_id: ID
	username: String! @unique
	email: String! 
	password: String!
	avatar: String
	joinDate: String
	favorites: [Pet]
}
type Animal {
	_id: ID
	name: String! @unique 
	description: String
	image: String
	createdDate: String
}
type Pet {
	name: String! 
	description: String
	race: Animal!
	image: String
	createdDate: String
	likes: Int
	createdBy: User!
	comments: [Comments]
}
type Comments {
	_id: ID
	commentBody: String!
	commentDate: String
	commentUser: String!
}

type Query {
	getPets: [Pet],
	getAnimals: [Animal]
},

type Mutation {
	signupUser(
		username: String!, 
		email: String!,
		password: String!
	):User!

	addAnimal(
		name: String!,
		description: String, 
		image: String,		
	):Animal!

	addPet(
		name: String!,
		description: String, 
		raceID: ID!, 
		image: String, 
		creatorID: ID!
	):Pet!
}